<a href="https://colab.research.google.com/github/Dheeraj2002kumar/Python_with_Data_Science/blob/main/8_Python_with_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy
NumPy is a library having functionalities related to Numerical Python

Core Python Data Types
- int, float, complex, bool
- str, list, tuple, dict, set

##### NumPy contains a data type called as ndarray (N-dimensional array)
- This is the most important object of the NumPY Module

In [ ]:
l = [2, 9, 1, 8]
l

[2, 9, 1, 8]

### Array
It is a collection of homogeneous data element/s

In [ ]:
la = np.array(l)
la

NameError: name 'np' is not defined

In [ ]:
# pip install numpy

Note: you may need to restart the kernel to use updated packages.


Modules
- Inbuilt
- User-defined
- External

In [ ]:
import numpy as np
l = [2, 9, 1, 8]
al = np.array(l)
al   # 0 Rows 4 columns

array([2, 9, 1, 8])

In [ ]:
l = [[2, 9, 1, 8]]
al1 = np.array(l)
al1

array([[2, 9, 1, 8]])

In [ ]:
al1.ndim

2

In [ ]:
al1.shape

(1, 4)

In [ ]:
al.ndim

1

In [ ]:
al.shape

(4,)

In [ ]:
print(al)

[2 9 1 8]


In [ ]:
k = [[2, 9, 1, 8],
     [6, 3, 2, 0]]
ak = np.array(k)
ak

array([[2, 9, 1, 8],
       [6, 3, 2, 0]])

In [ ]:
ak.ndim

2

In [ ]:
ak.shape

(2, 4)

In [ ]:
m = [[[2, 9, 1, 8],
      [6, 3, 2, 0]],
     [[7, 1, 1, 8],
      [6, 9, 2, 5]]]
am = np.array(m)
am

array([[[2, 9, 1, 8],
        [6, 3, 2, 0]],

       [[7, 1, 1, 8],
        [6, 9, 2, 5]]])

In [ ]:
am.shape

(2, 2, 4)

In [ ]:
am.size   # Total number of elements in th array

16

In [ ]:
am.ndim

3

In [ ]:
n = [[[2, 9, 1, 8],
      [6, 3, 2, 0]],
     [[7, 1, 1, 8],
      [6, 9, 2, 5]]]
dpn = np.array(n)
dpn

array([[[2, 9, 1, 8],
        [6, 3, 2, 0]],

       [[7, 1, 1, 8],
        [6, 9, 2, 5]]])

In [ ]:
n = [[[2, 9, 1, 8],
      [6, 3, 2.3, 0]],
     [[7, 1, 1, 8],
      [6, 9, 2, 5]]]
dpn = np.array(n)
dpn

array([[[2. , 9. , 1. , 8. ],
        [6. , 3. , 2.3, 0. ]],

       [[7. , 1. , 1. , 8. ],
        [6. , 9. , 2. , 5. ]]])

In [ ]:
n = [[[2, 9, 1, 8],
      [6, 3, 2, 0]],
     [[7, 1, 1, 8],
      [6, 9, 'a', 5]]]
dpn = np.array(n)
dpn

array([[['2', '9', '1', '8'],
        ['6', '3', '2', '0']],

       [['7', '1', '1', '8'],
        ['6', '9', 'a', '5']]], dtype='<U11')

In [ ]:
n = [[[2, 9, 1, 8],
      [6, 3, 2, 0]],
     [[7, 1, 1, 8],
      [6, 9, 2, 5]]]
dpn = np.array(n, dtype = 'float')
dpn

array([[[2., 9., 1., 8.],
        [6., 3., 2., 0.]],

       [[7., 1., 1., 8.],
        [6., 9., 2., 5.]]])

In [ ]:
# Create an array of 10 integers
q = []
for i in range(10):
    q.append(i)
np.array(q)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Indexing in Array

In [ ]:
am

array([[[2, 9, 1, 8],
        [6, 3, 2, 0]],

       [[7, 1, 1, 8],
        [6, 9, 2, 5]]])

In [ ]:
am.shape  # (layer, row, column)

(2, 2, 4)

In [ ]:
am[0]

array([[2, 9, 1, 8],
       [6, 3, 2, 0]])

In [ ]:
am[0][0]

array([2, 9, 1, 8])

In [ ]:
am[0][0][0]

2

In [ ]:
am[1]

array([[7, 1, 1, 8],
       [6, 9, 2, 5]])

In [ ]:
am[2]

IndexError: index 2 is out of bounds for axis 0 with size 2

#### Integer Array Indexing

In [ ]:
ak

array([[2, 9, 1, 8],
       [6, 3, 2, 0]])

In [ ]:
ak[[0, 1],[2, 0]]   # Row Coordinates, Column Coordinates

array([1, 6])

In [ ]:
am

array([[[2, 9, 1, 8],
        [6, 3, 2, 0]],

       [[7, 1, 1, 8],
        [6, 9, 2, 5]]])

In [ ]:
am[[0],[1],[1]]

array([3])

#### Boolean Array Indexing

In [ ]:
ak

array([[2, 9, 1, 8],
       [6, 3, 2, 0]])

In [ ]:
ak[ak < 7]

array([2, 1, 6, 3, 2, 0])

In [ ]:
ak[ak %2 == 0]

array([2, 8, 6, 2, 0])

#### Slicing

In [ ]:
ak

array([[2, 9, 1, 8],
       [6, 3, 2, 0]])

In [ ]:
ak[:,1:2]     # Row Slicing, Column Sling

array([[9],
       [3]])

In [ ]:
p = [[2, 9, 1, 8],
      [6, 3, 2, 0],
      [7, 1, 1, 8]]
ap = np.array(p)
ap

array([[2, 9, 1, 8],
       [6, 3, 2, 0],
       [7, 1, 1, 8]])

In [ ]:
ap[1:,2:]

array([[2, 0],
       [1, 8]])

In [ ]:
ap

array([[2, 9, 1, 8],
       [6, 3, 2, 0],
       [7, 1, 1, 8]])

In [ ]:
ap[1][3]

0

In [ ]:
ap[1][3] = 52
ap

array([[ 2,  9,  1,  8],
       [ 6,  3,  2, 52],
       [ 7,  1,  1,  8]])

In [ ]:
# Create an array having all elemernts as zero of the shape (3, 2, 4)
q=[]
for i in range(4):
    q.append(0)
r=[[q,q],[q,q],[q,q]]
ar=np.array(r)

ar

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [ ]:
ar = np.zeros((3, 2, 4))
ar

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.zeros((3, 2, 4), dtype = 'int')

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [ ]:
np.ones((3, 2, 4), dtype = 'int')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [ ]:
np.full((3, 2, 4), 5)

array([[[5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5]]])

In [ ]:
np.full((3, 2, 4), 'hi')

array([[['hi', 'hi', 'hi', 'hi'],
        ['hi', 'hi', 'hi', 'hi']],

       [['hi', 'hi', 'hi', 'hi'],
        ['hi', 'hi', 'hi', 'hi']],

       [['hi', 'hi', 'hi', 'hi'],
        ['hi', 'hi', 'hi', 'hi']]], dtype='<U2')